### ISSUE TITLE
Getting this using github actions

### ISSUE THREAD

**Issue by PockySweet** [erikaheidi/dynacover#20]
```console
Generating new cover...

Fatal error: Uncaught TypeError: Argument 2 passed to GDaisy\Placeholder\ImagePlaceholder::apply() must be of the type array, null given, called in /dynacover/app/Command/Generate/TwitterController.php on line 61 and defined in /dynacover/vendor/erikaheidi/gdaisy/src/Placeholder/ImagePlaceholder.php:35
Stack trace:
#0 /dynacover/app/Command/Generate/TwitterController.php(61): GDaisy\Placeholder\ImagePlaceholder->apply(Resource id #69, NULL)
#1 /dynacover/vendor/minicli/minicli/src/Command/CommandController.php(38): App\Command\Generate\TwitterController->handle()
#2 /dynacover/vendor/minicli/minicli/src/App.php(159): Minicli\Command\CommandController->run(Object(Minicli\Command\CommandCall))
#3 /dynacover/app/Command/Cover/UpdateController.php(15): Minicli\App->runCommand(Array)
#4 /dynacover/vendor/minicli/minicli/src/Command/CommandController.php(38): App\Command\Cover\UpdateController->handle()
#5 /dynacover/vendor/minicli/minicli/src/App.php(159): Minicli\Command\CommandController->run(Object(Minicli\Command\CommandCa in /dynacover/vendor/erikaheidi/gdaisy/src/Placeholder/ImagePlaceholder.php on line 35
```

**Comment by PockySweet** [comment]
My config file
```json
{
  "width": 1500,
  "height": 500,
  "sources": {
    "twitter": {
      "count": 3,
      "class": "App\\ImageSource\\TwitterFollowerImageSource"
    }
  },
  "elements": {
    "tw1": {
      "type": "image",
      "properties": {
        "pos_x": 702,
        "pos_y": 435,
        "width": 94,
        "height": 94
      }
    },
    "tw2": {
      "type": "image",
      "properties": {
        "pos_x": 809,
        "pos_y": 435,
        "width": 94,
        "height": 94
      }
    },
    "tw3": {
      "type": "image",
      "properties": {
        "pos_x": 916,
        "pos_y": 435,
        "width": 94,
        "height": 94
      }
    },
    "cover": {
      "type": "image",
      "properties": {
        "width": 1500,
        "height": 500,
        "pos_x": 0,
        "pos_y": 0,
        "image": "background.png"
      }
    }
  }
}
```

**Comment by PockySweet** [comment]
My dynacover.yml file
```yml
name: Update Twitter Header Image with Dynacover
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'dynacover_custom'
      - name: 'Update Dynacover image and upload to Twitter'
        uses: erikaheidi/dynacover-actions@v4.2
        env:
          # Uncomment and change accordingly to customize your cover
          DYNA_DEFAULT_TEMPLATE: cover_bottom.json
          DYNA_TEMPLATES_DIR: ${{ github.workspace }}/dynacover_custom
          DYNA_IMAGES_DIR: ${{ github.workspace }}/dynacover_custom
          DYNA_TWITTER_KEY: ${{ secrets.DYNA_TWITTER_KEY }}
          DYNA_TWITTER_SECRET: ${{ secrets.DYNA_TWITTER_SECRET }}
          DYNA_TWITTER_TOKEN: ${{ secrets.DYNA_TWITTER_TOKEN }}
          DYNA_TWITTER_TOKEN_SECRET: ${{ secrets.DYNA_TWITTER_TOKEN_SECRET }}
          DYNA_GITHUB_TOKEN: ${{ secrets.DYNA_GITHUB_TOKEN }}
```
